import UIKit
import FaceTecSDK

class ZoomViewController: UIViewController, URLSessionDelegate {

    var latestSessionResult: FaceTecSessionResult!
    var latestIDScanResult: FaceTecIDScanResult!
    var utils: SampleAppUtilities!
    var latestProcessor: Processor!
    var requestInProgress: Bool = false
    var isEnrolled = false
    
    override func viewDidLoad() {
        super.viewDidLoad()

        checkEnrollmentStatus()
        utils = SampleAppUtilities(vc: self)
        
        Config.initializeFaceTecSDKFromAutogeneratedConfig(completion: { initializationSuccessful in
            if(initializationSuccessful) {
                
            }
        })
    }

    func getSessionToken(sessionTokenCallback: @escaping (String) -> ()) {
        let endpoint = Config.BaseURL + "/session-token"
        let request = NSMutableURLRequest(url: NSURL(string: endpoint)! as URL)
        request.httpMethod = "GET"
        // Required parameters to interact with the FaceTec Managed Testing API.
        request.addValue(Config.DeviceKeyIdentifier, forHTTPHeaderField: "X-Device-Key")
        request.addValue(FaceTec.sdk.createFaceTecAPIUserAgentString("\(Helper.getPREF(UserDefaults.PREF_USERID) ?? "")"), forHTTPHeaderField: "User-Agent")
        
        let session = URLSession(configuration: URLSessionConfiguration.default, delegate: self, delegateQueue: OperationQueue.main)
        let task = session.dataTask(with: request as URLRequest, completionHandler: { data, response, error in
            // Ensure the data object is not nil otherwise callback with empty dictionary.
            guard let data = data else {
                print("Exception raised while attempting HTTPS call.")
                return
            }
            if let responseJSONObj = try? JSONSerialization.jsonObject(with: data, options: JSONSerialization.ReadingOptions.allowFragments) as? [String: AnyObject] {
                if((responseJSONObj["sessionToken"] as? String) != nil)
                {
                    sessionTokenCallback(responseJSONObj["sessionToken"] as! String)
                    return
                }
                else {
                    print("Exception raised while attempting HTTPS call.")
                }
            }
        })
        task.resume()
    }

    @IBAction func skipClicked(_ sender: UIButton) {
        if let vc = ViewControllerHelper.getViewController(ofType: .RegistrationCompletedViewController) as? RegistrationCompletedViewController {
            self.navigationController?.pushViewController(vc, animated: true)
        }
    }
    
    @IBAction func nextClicked(_ sender: UIButton) {
        if !isEnrolled {
            getSessionToken() { sessionToken in
                self.latestProcessor = EnrollmentProcessor(sessionToken: sessionToken, fromViewController: self)
            }
        }
        else {
            getSessionToken() { sessionToken in
                self.latestProcessor = AuthenticateProcessor(sessionToken: sessionToken, fromViewController: self)
            }
        }
    }
    
}

// MARK: - FACETECH CALLBACK
extension ZoomViewController {
    func onComplete() {
        if self.latestProcessor.isSuccess() {
            self.setEnrollmentStatus()
        }
    }
    
    func setLatestSessionResult(sessionResult: FaceTecSessionResult) {
        latestSessionResult = sessionResult
    }
    
    func setLatestIDScanResult(idScanResult: FaceTecIDScanResult) {
        latestIDScanResult = idScanResult
    }
    
    func setLatestServerResult(responseJSON: [String: AnyObject]) {
        print(responseJSON)
    }
}

// MARK: - API CALL
extension ZoomViewController {
    func checkEnrollmentStatus() {
        let params: [String: AnyObject] = [WSRequestParams.WS_REQS_PARAM_MOBILENO: Helper.getPREF(UserDefaults.PREF_MOBILE) as AnyObject]
        WSManager.wsCallCheckEnrollment(params) { (isSuccess) in
            if isSuccess {
                self.isEnrolled = true
            }
            else {
                self.isEnrolled = false
            }
        }
    }
    
    func setEnrollmentStatus() {
        let params: [String: AnyObject] = [WSRequestParams.WS_REQS_PARAM_MOBILENO: Helper.getPREF(UserDefaults.PREF_MOBILE) as AnyObject]
        WSManager.wsCallSetEnrollment(params) { (isSuccess) in
            if isSuccess {
                if let vc = ViewControllerHelper.getViewController(ofType: .RegistrationCompletedViewController) as? RegistrationCompletedViewController {
                    self.navigationController?.pushViewController(vc, animated: true)
                }
            }
        }
    }
}
